from waflib.extras.layout import Solution, Product

NAME = 'turbo'

def options(optCtx):
    optCtx.add_option('--test', action='store', default='', dest='test')

def configure(confCtx):
    confCtx.env.product = Product.fromContext(confCtx, NAME, confCtx.env.solution)
    confCtx.recurse('filesystem')
    confCtx.recurse('process')

def build(buildCtx):
    buildCtx.env.product = buildCtx.env.solution.getProduct(NAME)
    buildCtx.recurse('filesystem')
    buildCtx.recurse('process')
