from waflib.extras.layout import Solution, Product

NAME = 'turbo'

def options(optCtx):
    optCtx.add_option('--test', action='store', default='', dest='test')

def configure(confCtx):
    confCtx.env.product = Product.fromContext(confCtx, NAME, confCtx.env.solution)
    confCtx.recurse('toolset')
    confCtx.recurse('type_utility')
    confCtx.recurse('math')
    confCtx.recurse('threading')
    confCtx.recurse('algorithm')
    confCtx.recurse('container')
    confCtx.recurse('memory')
    confCtx.recurse('filesystem')
    confCtx.recurse('process')
    confCtx.recurse('cinterop')

def build(buildCtx):
    buildCtx.env.product = buildCtx.env.solution.getProduct(NAME)
    buildCtx.recurse('toolset')
    buildCtx.recurse('type_utility')
    buildCtx.recurse('math')
    buildCtx.recurse('threading')
    buildCtx.recurse('algorithm')
    buildCtx.recurse('container')
    buildCtx.recurse('memory')
    buildCtx.recurse('filesystem')
    buildCtx.recurse('process')
    buildCtx.recurse('cinterop')
