import os
from waflib.extras.layout import Product, Component

publicHeaders = [
    'bitwise_trie.hpp',
    'bitwise_trie.hh',
    'concurrent_list.hpp',
    'concurrent_list.hh',
    'concurrent_unordered_map.hpp',
    'concurrent_unordered_map.hh',
    'concurrent_vector.hpp',
    'concurrent_vector.hh',
    'emplacing_list.hpp',
    'emplacing_list.hh',
    'emplacing_skiplist.hpp',
    'emplacing_skiplist.hh',
    'heap.hpp',
    'heap.hh',
    'invalid_dereference_error.hpp',
    'mpmc_ring_queue.hpp',
    'mpmc_ring_queue.hh',
    'spsc_ring_queue.hpp',
    'spsc_ring_queue.hh',
    'trie_key.hpp']

def name(context):
    return os.path.basename(str(context.path))

def configure(confCtx):
    confCtx.env.component = Component.fromContext(confCtx, name(confCtx), confCtx.env.product)
    confCtx.env.product.addComponent(confCtx.env.component)

def build(buildCtx):
    buildCtx.env.component = buildCtx.env.product.getComponent(name(buildCtx))
    publishTaskList=[]
    for header in publicHeaders:
	publishTask='publish_%s' % header
	buildCtx(
		name=publishTask,
		rule='cp ${SRC} ${TGT}',
		source=header,
		target=os.path.join(buildCtx.env.component.build_tree.includePathFromBuild(buildCtx), header),
		install_path=os.path.join(buildCtx.env.component.install_tree.include, os.path.dirname(header)))
	publishTaskList.append(publishTask)
