from waflib.extras.layout import Solution, Product

NAME = 'turbo'

def options(optCtx):
    optCtx.load('cxx_env dep_resolver')

def prepare(prepCtx):
    prepCtx.options.dep_base_dir = prepCtx.srcnode.find_dir('..').abspath()
    prepCtx.load('cxx_env dep_resolver')

def configure(confCtx):
    confCtx.options.env_conf_dir = confCtx.srcnode.find_dir('env').abspath()
    confCtx.load('cxx_env dep_resolver')
    confCtx.env.product = Product.fromContext(confCtx, NAME, confCtx.env.solution)
    confCtx.env.solution.addProduct(confCtx.env.product)
    confCtx.env.product.include_path_list.append(confCtx.env.product.build_tree.include)
    confCtx.env.product.include_path_list.append(confCtx.env['INCLUDES_ASIO_SHLIB'])
    confCtx.env.product.include_path_list.append(confCtx.env['INCLUDES_ASIO_STLIB'])
    confCtx.env.product.include_path_list.append(confCtx.env['INCLUDES_GTEST'])
    confCtx.env.product.lib_path_list.append(confCtx.env['LIBPATH_ASIO_SHLIB'])
    confCtx.env.product.lib_path_list.append(confCtx.env['STLIBPATH_ASIO_STLIB'])
    confCtx.env.product.lib_path_list.append(confCtx.env['STLIBPATH_GTEST'])
    confCtx.env.product.rpath_list.append(confCtx.env['LIBPATH_ASIO_SHLIB'])
    confCtx.recurse('toolset')
    confCtx.recurse('type_utility')
    confCtx.recurse('math')
    confCtx.recurse('algorithm')
    confCtx.recurse('container')
    confCtx.recurse('memory')
    confCtx.recurse('filesystem')
    confCtx.recurse('ipc')
    confCtx.recurse('process')
    confCtx.recurse('cinterop')

def build(buildCtx):
    buildCtx.env.product = buildCtx.env.solution.getProduct(NAME)
    buildCtx.recurse('toolset')
    buildCtx.recurse('type_utility')
    buildCtx.recurse('math')
    buildCtx.recurse('algorithm')
    buildCtx.recurse('container')
    buildCtx.recurse('memory')
    buildCtx.recurse('filesystem')
    buildCtx.recurse('ipc')
    buildCtx.recurse('process')
    buildCtx.recurse('cinterop')
