import os
from waflib.extras.layout import Product, Component

def name(context):
    return os.path.basename(str(context.path))

def configure(confCtx):
    confCtx.env.component = Component.fromContext(confCtx, name(confCtx), confCtx.env.product)
    confCtx.env.product.addComponent(confCtx.env.component)

def build(buildCtx):
    buildCtx.program(
	    name='exe_spawn_child',
	    source=[buildCtx.path.find_node('posix/spawn_child.cxx')],
	    target=os.path.join(buildCtx.env.component.build_tree.testPathFromBuild(buildCtx), 'spawn_child'),
	    defines=['GTEST_HAS_PTHREAD=1'],
	    includes=['.'] + buildCtx.env.component.include_path_list,
	    cxxflags=buildCtx.env.CXXFLAGS,
	    linkflags=buildCtx.env.LDFLAGS,
	    libpath=['.'] + buildCtx.env.component.lib_path_list,
	    rpath=buildCtx.env.component.rpath_list,
	    install_path=buildCtx.env.component.install_tree.test,
	    after=['shlib_supernova_core', 'shlib_supernova_communication', 'shlib_supernova_storage'])
    buildCtx.program(
	    name='exe_spawn_test',
	    source=[buildCtx.path.find_node('posix/spawn_test.cxx')],
	    target=os.path.join(buildCtx.env.component.build_tree.testPathFromBuild(buildCtx), 'spawn_test'),
	    defines=['GTEST_HAS_PTHREAD=1'],
	    includes=['.'] + buildCtx.env.component.include_path_list,
	    cxxflags=buildCtx.env.CXXFLAGS,
	    linkflags=buildCtx.env.LDFLAGS,
	    use=['GTEST', 'shlib_turbo_ipc', 'shlib_turbo_process'],
	    libpath=['.'] + buildCtx.env.component.lib_path_list,
	    rpath=buildCtx.env.component.rpath_list,
	    install_path=buildCtx.env.component.install_tree.test,
	    after=['exe_spawn_child'])
